remove: Delete soder and beverage
StrataSource/Chaos-FGD pull request #171
Opened 2023-03-14 07:17 UTC by AWildErin

Internal code PR also removes them, though this can honestly be merged before

2023-03-14 07:18 UTC, JJL772 approved these changes

2023-03-17 12:18 UTC, hexaflexahexagon submitted a review, later dismissed

2023-03-18 06:52 UTC, JJL772 requested changes
They need to be removed from `db/factories` for both p2ce and momentum, and from visgroups.cfg

2023-03-18 15:14 UTC, AWildErin commented
Ah forgot about that, I can do that now

2023-03-18 16:56 UTC, JJL772 approved these changes

2023-03-18 16:56 UTC, merged